server:
  port: 80
spring:
  profiles:
    active: dev
  main.allow-bean-definition-overriding: true
  sql:
    init:
      encoding: UTF-8
  thymeleaf:
    prefix: classpath:templates/
    suffix: .html
logging.level:
  org.hibernate.SQL: debug
  

