spring:
  datasource:
#    url: jdbc:h2:tcp://localhost/~/animal-care-build
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
      url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/mysqlDb1
      username: root
      password: vision0223
      driver: com.mysql.cj.jdbc.Driver
      sql:
        init:
          encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace